'use strict';

// Search index for AI search (functions runtime)
module.exports.searchIndex = {
  pages: [
    { id: 'home', title: 'Home', url: '/', description: 'MLEbotics landing page.' },
    { id: 'projects', title: 'Projects', url: '/projects', description: 'Portfolio of personal and school projects.' },
    { id: 'blog', title: 'Blog', url: '/blog', description: 'Build logs and technical write-ups.' },
    { id: 'changelog', title: 'Changelog', url: '/changelog', description: 'Updates, releases, and milestones.' },
    { id: 'about', title: 'About', url: '/about', description: 'Mission, values, and background.' },
    { id: 'contact', title: 'Contact', url: '/contact', description: 'Get in touch with MLEbotics.' },
  ],
  projects: [
    {
      id: 'hey-girl',
      title: 'Hey Girl',
      url: '/projects',
      tagline: 'Voice AI assistant for Windows.',
      description: 'Wake-word activated voice assistant powered by GPT-4o.',
      tags: ['Python', 'GPT-4o', 'Voice', 'Windows', 'Telegram'],
      category: 'personal',
      year: 2025,
    },
    {
      id: 'run-companion',
      title: 'RunCompanion',
      url: '/projects',
      tagline: 'AI-powered running coach.',
      description: 'Flutter app with GPS tracking, Bluetooth HR, and Gemini AI coaching.',
      tags: ['Flutter', 'Dart', 'Gemini AI', 'Bluetooth', 'Firebase'],
      category: 'personal',
      year: 2025,
    },
    {
      id: 'auto-form-filler',
      title: 'AutoFormFiller',
      url: '/projects',
      tagline: 'AI-powered Chrome form automation.',
      description: 'Chrome extension + Flask backend using GPT-4o vision for forms.',
      tags: ['Python', 'Flask', 'Chrome Extension', 'GPT-4o', 'AWS'],
      category: 'personal',
      year: 2024,
    },
    {
      id: 'computer-use',
      title: 'Computer Use',
      url: '/projects',
      tagline: 'AI agent that controls your desktop.',
      description: 'Desktop automation agent built on Anthropic Computer Use API.',
      tags: ['Python', 'Anthropic', 'Desktop AI', 'Automation'],
      category: 'personal',
      year: 2025,
    },
    {
      id: 'mlebotics-hub',
      title: 'MLEbotics Hub',
      url: '/projects',
      tagline: 'One launcher for all MLEbotics tools.',
      description: 'Desktop app bundling Hey Girl, Computer Use, AutoFormFiller.',
      tags: ['Python', 'PyInstaller', 'Desktop', 'Windows'],
      category: 'personal',
      year: 2025,
    },
    {
      id: 'stock-pulse',
      title: 'StockPulse',
      url: '/projects',
      tagline: 'Live stock ticker React app.',
      description: 'React SPA with Finnhub API and interactive charts.',
      tags: ['React', 'Vite', 'Finnhub API', 'Chart.js'],
      category: 'school',
      year: 2025,
    },
    {
      id: 'movie-browser',
      title: 'Movie Browser',
      url: '/projects',
      tagline: 'TMDB movie browser with React Portals.',
      description: 'React SPA with TMDB API search, genres, pagination, portals.',
      tags: ['React', 'TMDB API', 'React Router', 'CSS Modules'],
      category: 'school',
      year: 2025,
    },
  ],
  posts: [
    {
      id: 'why-i-built-runcompanion',
      title: 'Why I Built RunCompanion',
      url: '/blog/why-i-built-runcompanion',
      excerpt: 'From frustration to a full-stack Flutter app with AI coaching.',
      tags: ['Flutter', 'AI', 'Mobile', 'RunCompanion'],
      category: 'Project',
      date: '2025-11-12',
    },
    {
      id: 'islands-architecture-astro',
      title: 'Islands Architecture in Astro',
      url: '/blog/islands-architecture-astro',
      excerpt: 'Why Astro islands fit MLEbotics and how it was implemented.',
      tags: ['Astro', 'Web', 'Architecture'],
      category: 'Tech',
      date: '2025-12-02',
    },
    {
      id: 'hey-girl-voice-ai-windows',
      title: 'Hey Girl: Voice AI on Windows',
      url: '/blog/hey-girl-voice-ai-windows',
      excerpt: 'Wake-word, memory, and voice UX design choices.',
      tags: ['Voice', 'AI', 'Windows'],
      category: 'Project',
      date: '2025-10-03',
    },
    {
      id: 'autoformfiller-building-chrome-extension',
      title: 'AutoFormFiller: Building a Chrome Extension',
      url: '/blog/autoformfiller-building-chrome-extension',
      excerpt: 'OCR, vision models, and multi-page form handling.',
      tags: ['Chrome Extension', 'GPT-4o', 'Automation'],
      category: 'Project',
      date: '2025-09-18',
    },
  ],
};
